--ETL by date
INSERT INTO FACT_SALE
SELECT T.TIME_ID, BB.EMP_ID, BB.CLINIC_ID, BB.DOCTOR_ID, BB.TOTAL_AMOUNT
FROM (
         SELECT TRUNC(B.BILL_DATE) AS BILL_DATE, B.EMP_ID, B.CLINIC_ID, B.DOCTOR_ID, SUM(B.TOTAL_AMOUNT) AS TOTAL_AMOUNT
         FROM BILL B WHERE TRUNC(B.Bill_DATE)  = TO_DATE('2021/12/05', 'YYYY/MM/DD')
         GROUP BY TRUNC(B.BILL_DATE), B.EMP_ID, B.CLINIC_ID, B.DOCTOR_ID
     ) BB
INNER JOIN DIM_TIME T ON TRUNC(T.DATE_AT) = BB.BILL_DATE;


