DROP SEQUENCE SALARY_RANGE_SEQ;
DROP SEQUENCE CUSTOMER_SEQ;
DROP SEQUENCE DOCTOR_SEQ;
DROP SEQUENCE CLINIC_SEQ;
DROP SEQUENCE SALES_STAFF_SEQ;
DROP SEQUENCE SPECIALIST_SEQ;
DROP SEQUENCE DOCTOR_SPECIALIST_SEQ;
DROP SEQUENCE OPERATION_SEQ;
DROP SEQUENCE PRODUCT_USE_SEQ;
DROP SEQUENCE BILL_SEQ;
DROP SEQUENCE BILL_OPERATION_SEQ;
DROP SEQUENCE BILL_NO_SEQ;


CREATE SEQUENCE SALARY_RANGE_SEQ START WITH 1;
CREATE SEQUENCE CUSTOMER_SEQ START WITH 1;
CREATE SEQUENCE DOCTOR_SEQ START WITH 1;
CREATE SEQUENCE CLINIC_SEQ START WITH 1;
CREATE SEQUENCE SALES_STAFF_SEQ START WITH 1;
CREATE SEQUENCE SPECIALIST_SEQ START WITH 1;
CREATE SEQUENCE DOCTOR_SPECIALIST_SEQ START WITH 1;
CREATE SEQUENCE OPERATION_SEQ START WITH 1;
CREATE SEQUENCE PRODUCT_USE_SEQ START WITH 1;
CREATE SEQUENCE BILL_SEQ START WITH 1;
CREATE SEQUENCE BILL_OPERATION_SEQ START WITH 1;
CREATE SEQUENCE BILL_NO_SEQ START WITH 1;



INSERT INTO SALARY_RANGE (SALARY_RANGE_ID, RANGE_START, RANGE_END) VALUES (SALARY_RANGE_SEQ.NEXTVAL, 0.00, 10000.00);
INSERT INTO SALARY_RANGE (SALARY_RANGE_ID, RANGE_START, RANGE_END) VALUES (SALARY_RANGE_SEQ.NEXTVAL, 10000.00, 20000.00);
INSERT INTO SALARY_RANGE (SALARY_RANGE_ID, RANGE_START, RANGE_END) VALUES (SALARY_RANGE_SEQ.NEXTVAL, 20000.00, 30000.00);
INSERT INTO SALARY_RANGE (SALARY_RANGE_ID, RANGE_START, RANGE_END) VALUES (SALARY_RANGE_SEQ.NEXTVAL, 30000.00, 40000.00);

--- CUSTOMER ----
INSERT INTO CUSTOMER (CUSTOMER_ID, FULL_NAME, BIRTHDAY, SEX, SALARY_RANGE_ID, WORK_LOCATION, SKIN_PROBLEM, CONTACT, ALLERGY) VALUES (CUSTOMER_SEQ.NEXTVAL, 'มีนา  นาสาร', TO_DATE('1986-12-06 18:15:58', 'YYYY-MM-DD HH24:MI:SS'), 'F', 2, 'พระราม 9', null, '0912321232', null);
INSERT INTO CUSTOMER (CUSTOMER_ID, FULL_NAME, BIRTHDAY, SEX, SALARY_RANGE_ID, WORK_LOCATION, SKIN_PROBLEM, CONTACT, ALLERGY) VALUES (CUSTOMER_SEQ.NEXTVAL,'ธนสมบัติ เก่งทำงาน', TO_DATE('1986-12-06 18:15:58', 'YYYY-MM-DD HH24:MI:SS'), 'F', 2, 'พระราม 9', null, '0912321232', null);
INSERT INTO CUSTOMER (CUSTOMER_ID, FULL_NAME, BIRTHDAY, SEX, SALARY_RANGE_ID, WORK_LOCATION, SKIN_PROBLEM, CONTACT, ALLERGY) VALUES (CUSTOMER_SEQ.NEXTVAL,'ศักดิ์คีรี คล่องการงาน', TO_DATE('1986-12-06 18:15:58', 'YYYY-MM-DD HH24:MI:SS'), 'F', 3, 'พระราม 9', null, '0912321232', null);
INSERT INTO CUSTOMER (CUSTOMER_ID, FULL_NAME, BIRTHDAY, SEX, SALARY_RANGE_ID, WORK_LOCATION, SKIN_PROBLEM, CONTACT, ALLERGY) VALUES (CUSTOMER_SEQ.NEXTVAL,'วนาลี ใจบริสุทธิ์', TO_DATE('1986-12-06 18:15:58', 'YYYY-MM-DD HH24:MI:SS'), 'F', 4, 'พระราม 9', null, '0912321232', null);
INSERT INTO CUSTOMER (CUSTOMER_ID, FULL_NAME, BIRTHDAY, SEX, SALARY_RANGE_ID, WORK_LOCATION, SKIN_PROBLEM, CONTACT, ALLERGY) VALUES (CUSTOMER_SEQ.NEXTVAL,'คณิน ค้าขายดี', TO_DATE('1986-12-06 18:15:58', 'YYYY-MM-DD HH24:MI:SS'), 'F', 1, 'พระราม 9', null, '0912321232', null);
INSERT INTO CUSTOMER (CUSTOMER_ID, FULL_NAME, BIRTHDAY, SEX, SALARY_RANGE_ID, WORK_LOCATION, SKIN_PROBLEM, CONTACT, ALLERGY) VALUES (CUSTOMER_SEQ.NEXTVAL,'ธนบัตร ทำกินเก่ง', TO_DATE('1986-12-06 18:15:58', 'YYYY-MM-DD HH24:MI:SS'), 'F', 2, 'พระราม 9', null, '0912321232', null);
INSERT INTO CUSTOMER (CUSTOMER_ID, FULL_NAME, BIRTHDAY, SEX, SALARY_RANGE_ID, WORK_LOCATION, SKIN_PROBLEM, CONTACT, ALLERGY) VALUES (CUSTOMER_SEQ.NEXTVAL,'รณชัย จิตแจ่มใส', TO_DATE('1986-12-06 18:15:58', 'YYYY-MM-DD HH24:MI:SS'), 'F', 3, 'พระราม 9', null, '0912321232', null);
INSERT INTO CUSTOMER (CUSTOMER_ID, FULL_NAME, BIRTHDAY, SEX, SALARY_RANGE_ID, WORK_LOCATION, SKIN_PROBLEM, CONTACT, ALLERGY) VALUES (CUSTOMER_SEQ.NEXTVAL,'พีรญา คล่องการค้า', TO_DATE('1986-12-06 18:15:58', 'YYYY-MM-DD HH24:MI:SS'), 'F', 4, 'พระราม 9', null, '0912321232', null);
INSERT INTO CUSTOMER (CUSTOMER_ID, FULL_NAME, BIRTHDAY, SEX, SALARY_RANGE_ID, WORK_LOCATION, SKIN_PROBLEM, CONTACT, ALLERGY) VALUES (CUSTOMER_SEQ.NEXTVAL,'ญาดา ชอบอาสา', TO_DATE('1986-12-06 18:15:58', 'YYYY-MM-DD HH24:MI:SS'), 'F', 1, 'พระราม 9', null, '0912321232', null);
INSERT INTO CUSTOMER (CUSTOMER_ID, FULL_NAME, BIRTHDAY, SEX, SALARY_RANGE_ID, WORK_LOCATION, SKIN_PROBLEM, CONTACT, ALLERGY) VALUES (CUSTOMER_SEQ.NEXTVAL,'วรกุล ทองอร่าม', TO_DATE('1986-12-06 18:15:58', 'YYYY-MM-DD HH24:MI:SS'), 'F', 2, 'พระราม 9', null, '0912321232', null);
INSERT INTO CUSTOMER (CUSTOMER_ID, FULL_NAME, BIRTHDAY, SEX, SALARY_RANGE_ID, WORK_LOCATION, SKIN_PROBLEM, CONTACT, ALLERGY) VALUES (CUSTOMER_SEQ.NEXTVAL,'พอฤทัย ใจปราณี', TO_DATE('1986-12-06 18:15:58', 'YYYY-MM-DD HH24:MI:SS'), 'F', 3, 'พระราม 9', null, '0912321232', null);
INSERT INTO CUSTOMER (CUSTOMER_ID, FULL_NAME, BIRTHDAY, SEX, SALARY_RANGE_ID, WORK_LOCATION, SKIN_PROBLEM, CONTACT, ALLERGY) VALUES (CUSTOMER_SEQ.NEXTVAL,'ธนบัตร ปัญญาดี', TO_DATE('1986-12-06 18:15:58', 'YYYY-MM-DD HH24:MI:SS'), 'F', 4, 'พระราม 9', null, '0912321232', null);
INSERT INTO CUSTOMER (CUSTOMER_ID, FULL_NAME, BIRTHDAY, SEX, SALARY_RANGE_ID, WORK_LOCATION, SKIN_PROBLEM, CONTACT, ALLERGY) VALUES (CUSTOMER_SEQ.NEXTVAL,'มนตรา รักษาสัตย์', TO_DATE('1986-12-06 18:15:58', 'YYYY-MM-DD HH24:MI:SS'), 'F', 1, 'พระราม 9', null, '0912321232', null);
INSERT INTO CUSTOMER (CUSTOMER_ID, FULL_NAME, BIRTHDAY, SEX, SALARY_RANGE_ID, WORK_LOCATION, SKIN_PROBLEM, CONTACT, ALLERGY) VALUES (CUSTOMER_SEQ.NEXTVAL,'วรวิทย์ จิตแจ่มใส', TO_DATE('1986-12-06 18:15:58', 'YYYY-MM-DD HH24:MI:SS'), 'F', 2, 'พระราม 9', null, '0912321232', null);
INSERT INTO CUSTOMER (CUSTOMER_ID, FULL_NAME, BIRTHDAY, SEX, SALARY_RANGE_ID, WORK_LOCATION, SKIN_PROBLEM, CONTACT, ALLERGY) VALUES (CUSTOMER_SEQ.NEXTVAL,'บูรณิศา ตั้งใจเรียน', TO_DATE('1986-12-06 18:15:58', 'YYYY-MM-DD HH24:MI:SS'), 'F', 3, 'พระราม 9', null, '0912321232', null);
INSERT INTO CUSTOMER (CUSTOMER_ID, FULL_NAME, BIRTHDAY, SEX, SALARY_RANGE_ID, WORK_LOCATION, SKIN_PROBLEM, CONTACT, ALLERGY) VALUES (CUSTOMER_SEQ.NEXTVAL,'กฤษฎา ตั้งใจดี', TO_DATE('1986-12-06 18:15:58', 'YYYY-MM-DD HH24:MI:SS'), 'F', 3, 'พระราม 9', null, '0912321232', null);
INSERT INTO CUSTOMER (CUSTOMER_ID, FULL_NAME, BIRTHDAY, SEX, SALARY_RANGE_ID, WORK_LOCATION, SKIN_PROBLEM, CONTACT, ALLERGY) VALUES (CUSTOMER_SEQ.NEXTVAL,'ภัทรา งามน้ำใจ', TO_DATE('1986-12-06 18:15:58', 'YYYY-MM-DD HH24:MI:SS'), 'F', 2, 'พระราม 9', null, '0912321232', null);

--- DOCTOR ----
INSERT INTO DOCTOR (DOCTOR_ID, DOCTOR_FULL_NAME, CONTACT, SALARY, ADDRESS, STARTING_DATE, SEX, AGE, BIRTHDAY, LICENSE_NUMBER) VALUES (DOCTOR_SEQ.NEXTVAL, 'มีชัย ผิวลาม', 'คอนโด ลาดพร้าว', 10000, 'คอนโด ลาดพร้าว', TO_DATE('2021-12-03 16:04:17', 'YYYY-MM-DD HH24:MI:SS'), 'M', 30, TO_DATE('1990-12-03 16:04:30', 'YYYY-MM-DD HH24:MI:SS'), '123456789');
INSERT INTO DOCTOR (DOCTOR_ID, DOCTOR_FULL_NAME, CONTACT, SALARY, ADDRESS, STARTING_DATE, SEX, AGE, BIRTHDAY, LICENSE_NUMBER) VALUES (DOCTOR_SEQ.NEXTVAL, 'กรรชัย ศรีราม', 'คอนโด จตุจักร', 200000, 'คอนโด จตุจักร', TO_DATE('2021-12-03 16:04:17', 'YYYY-MM-DD HH24:MI:SS'), 'M', 40, TO_DATE('1990-12-03 16:04:30', 'YYYY-MM-DD HH24:MI:SS'), 'E00123212');

--- CLINIC ----
INSERT INTO CLINIC (CLINIC_ID, CLINIC_NAME, LANDMARK, LOCATION) VALUES (CLINIC_SEQ.NEXTVAL, 'เซนทรัล ลาดพร้าว', 'เซนทรัล ลาดพร้าว', 'ลาดพร้าว');
INSERT INTO CLINIC (CLINIC_ID, CLINIC_NAME, LANDMARK, LOCATION) VALUES (CLINIC_SEQ.NEXTVAL, 'พระราม 9', 'เซนทรัล พระราม 9', 'พระราม9');


INSERT INTO SALES_STAFF (EMP_ID, EMP_FULL_NAME, CONTACT, SALARY, HOME_ADDRESS, STARTING_DATE, WORK_BRANCH, SEX, AGE, BIRTH_DATE, SALES_PERFORMANCE) VALUES (SALES_STAFF_SEQ.NEXTVAL, 'มั่นใจ  ดีมาก', '012312322', 12000, 'ลาดพร้าว', TO_DATE('2021-12-06 23:32:23', 'YYYY-MM-DD HH24:MI:SS'), 'ลาดพร้าว', 'M', 40, TO_DATE('1988-12-06 23:32:37', 'YYYY-MM-DD HH24:MI:SS'), null);
INSERT INTO SALES_STAFF (EMP_ID, EMP_FULL_NAME, CONTACT, SALARY, HOME_ADDRESS, STARTING_DATE, WORK_BRANCH, SEX, AGE, BIRTH_DATE, SALES_PERFORMANCE) VALUES (SALES_STAFF_SEQ.NEXTVAL, 'ขยัน  มั่นคง', '081232123', 12000, 'ลาดพร้าว', TO_DATE('2021-12-06 23:32:23', 'YYYY-MM-DD HH24:MI:SS'), 'ลาดพร้าว', 'M', 40, TO_DATE('1988-12-06 23:32:37', 'YYYY-MM-DD HH24:MI:SS'), null);


INSERT INTO SPECIALIST (SPECIALIST_ID, NAME) VALUES (SPECIALIST_SEQ.NEXTVAL, 'ผิวหนัง');
INSERT INTO SPECIALIST (SPECIALIST_ID, NAME) VALUES (SPECIALIST_SEQ.NEXTVAL, 'ศัลยกรรม');
INSERT INTO SPECIALIST (SPECIALIST_ID, NAME) VALUES (SPECIALIST_SEQ.NEXTVAL, 'ฟัน');


INSERT INTO DOCTOR_SPECIALIST (DOCTOR_SPECIALIST_ID, DOCTOR_ID, SPECIALIST_ID) VALUES (DOCTOR_SPECIALIST_SEQ.NEXTVAL, 2, 1);
INSERT INTO DOCTOR_SPECIALIST (DOCTOR_SPECIALIST_ID, DOCTOR_ID, SPECIALIST_ID) VALUES (DOCTOR_SPECIALIST_SEQ.NEXTVAL, 2, 2);
INSERT INTO DOCTOR_SPECIALIST (DOCTOR_SPECIALIST_ID, DOCTOR_ID, SPECIALIST_ID) VALUES (DOCTOR_SPECIALIST_SEQ.NEXTVAL, 1, 3);


INSERT INTO OPERATION (OP_ID, NAME) VALUES (OPERATION_SEQ.NEXTVAL, 'ร้อยไหม');
INSERT INTO OPERATION (OP_ID, NAME) VALUES (OPERATION_SEQ.NEXTVAL, 'คอร์สเจ้าสาว');
INSERT INTO OPERATION (OP_ID, NAME) VALUES (OPERATION_SEQ.NEXTVAL, 'ดูดไขมัน');


INSERT INTO PRODUCT_USE (PRODUCT_ID, PRODUCT_NAME, GENERIC_NAME, BRAND, PROFIT_MARGIN, SELL_PRICE, COST, COUNTRY_OF_ORIGIN, QTY) VALUES (PRODUCT_USE_SEQ.NEXTVAL, 'ไหมละลาย', 'ไหมละลาย', 'Sripha', null, 100.00, 10.00, 'THAILAND', 100);
INSERT INTO PRODUCT_USE (PRODUCT_ID, PRODUCT_NAME, GENERIC_NAME, BRAND, PROFIT_MARGIN, SELL_PRICE, COST, COUNTRY_OF_ORIGIN, QTY) VALUES (PRODUCT_USE_SEQ.NEXTVAL, 'น้ำมันสมุนไพร', 'น้ำมันสมุนไพร', 'Sripha', null, 90.00, 10.00, 'THAILAND', 100);
INSERT INTO PRODUCT_USE (PRODUCT_ID, PRODUCT_NAME, GENERIC_NAME, BRAND, PROFIT_MARGIN, SELL_PRICE, COST, COUNTRY_OF_ORIGIN, QTY) VALUES (PRODUCT_USE_SEQ.NEXTVAL, 'A’Pura Natural', 'A’Pura Natural', 'Sripha', null, 100.00, 10.00, 'THAILAND', 100);
INSERT INTO PRODUCT_USE (PRODUCT_ID, PRODUCT_NAME, GENERIC_NAME, BRAND, PROFIT_MARGIN, SELL_PRICE, COST, COUNTRY_OF_ORIGIN, QTY) VALUES (PRODUCT_USE_SEQ.NEXTVAL, 'Daily Green Organic', 'Daily Green Organic', 'Sripha', null, 120.00, 10.00, 'THAILAND', 100);
INSERT INTO PRODUCT_USE (PRODUCT_ID, PRODUCT_NAME, GENERIC_NAME, BRAND, PROFIT_MARGIN, SELL_PRICE, COST, COUNTRY_OF_ORIGIN, QTY) VALUES (PRODUCT_USE_SEQ.NEXTVAL, 'La’Miat', 'La’Miat', 'Sripha', null, 70.00, 10.00, 'THAILAND', 100);
INSERT INTO PRODUCT_USE (PRODUCT_ID, PRODUCT_NAME, GENERIC_NAME, BRAND, PROFIT_MARGIN, SELL_PRICE, COST, COUNTRY_OF_ORIGIN, QTY) VALUES (PRODUCT_USE_SEQ.NEXTVAL, 'Zantiis', 'Zantiis', 'Sripha', null, 60.00, 10.00, 'THAILAND', 100);
INSERT INTO PRODUCT_USE (PRODUCT_ID, PRODUCT_NAME, GENERIC_NAME, BRAND, PROFIT_MARGIN, SELL_PRICE, COST, COUNTRY_OF_ORIGIN, QTY) VALUES (PRODUCT_USE_SEQ.NEXTVAL, 'Kalapa', 'Kalapa', 'Sripha', null, 30.00, 10.00, 'THAILAND', 100);
INSERT INTO PRODUCT_USE (PRODUCT_ID, PRODUCT_NAME, GENERIC_NAME, BRAND, PROFIT_MARGIN, SELL_PRICE, COST, COUNTRY_OF_ORIGIN, QTY) VALUES (PRODUCT_USE_SEQ.NEXTVAL, 'Khun', 'Khun', 'Sripha', null, 100.00, 10.00, 'THAILAND', 100);
INSERT INTO PRODUCT_USE (PRODUCT_ID, PRODUCT_NAME, GENERIC_NAME, BRAND, PROFIT_MARGIN, SELL_PRICE, COST, COUNTRY_OF_ORIGIN, QTY) VALUES (PRODUCT_USE_SEQ.NEXTVAL, 'Just Gentle', 'Just Gentle', 'Sripha', null, 110.00, 10.00, 'THAILAND', 100);


INSERT INTO BILL (BILL_ID,CLINIC_ID, DOCTOR_ID, EMP_ID, CUSTOMER_ID, BILL_NUMBER, BILL_DATE, DOCTOR_REQUEST, TOTAL_AMOUNT, WEIGHT, PRESSURE) VALUES (BILL_SEQ.NEXTVAL,1, 1, 1, 1, LPAD(BILL_NO_SEQ.nextval, 10, '0'), TO_TIMESTAMP('2021-12-06 23:58:55.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null, 100, 80.00, 120);
INSERT INTO BILL (BILL_ID,CLINIC_ID, DOCTOR_ID, EMP_ID, CUSTOMER_ID, BILL_NUMBER, BILL_DATE, DOCTOR_REQUEST, TOTAL_AMOUNT, WEIGHT, PRESSURE) VALUES (BILL_SEQ.NEXTVAL,1, 1, 1, 1, LPAD(BILL_NO_SEQ.nextval, 10, '0'), TO_TIMESTAMP('2021-12-05 23:58:55.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null, 120, 70.00, 119);
INSERT INTO BILL (BILL_ID,CLINIC_ID, DOCTOR_ID, EMP_ID, CUSTOMER_ID, BILL_NUMBER, BILL_DATE, DOCTOR_REQUEST, TOTAL_AMOUNT, WEIGHT, PRESSURE) VALUES (BILL_SEQ.NEXTVAL,1, 1, 2, 1, LPAD(BILL_NO_SEQ.nextval, 10, '0'), TO_TIMESTAMP('2021-12-05 23:58:55.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null, 120, 70.00, 119);
INSERT INTO BILL (BILL_ID,CLINIC_ID, DOCTOR_ID, EMP_ID, CUSTOMER_ID, BILL_NUMBER, BILL_DATE, DOCTOR_REQUEST, TOTAL_AMOUNT, WEIGHT, PRESSURE) VALUES (BILL_SEQ.NEXTVAL,1, 1, 2, 1, LPAD(BILL_NO_SEQ.nextval, 10, '0'), TO_TIMESTAMP('2021-12-05 23:58:55.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null, 120, 70.00, 119);


INSERT INTO BILL_OPERATION (BO_ID, OP_ID, BILL_ID) VALUES (BILL_OPERATION_SEQ.NEXTVAL, 1, 1);
INSERT INTO BILL_OPERATION (BO_ID, OP_ID, BILL_ID) VALUES (BILL_OPERATION_SEQ.NEXTVAL, 2, 1);
INSERT INTO BILL_OPERATION (BO_ID, OP_ID, BILL_ID) VALUES (BILL_OPERATION_SEQ.NEXTVAL, 2, 2);
INSERT INTO BILL_OPERATION (BO_ID, OP_ID, BILL_ID) VALUES (BILL_OPERATION_SEQ.NEXTVAL, 2, 3);
INSERT INTO BILL_OPERATION (BO_ID, OP_ID, BILL_ID) VALUES (BILL_OPERATION_SEQ.NEXTVAL, 2, 4);

INSERT INTO OPERATION_PRODUCT (OPERATION_PRODUCT_ID, OP_ID, QUANTITY, SALE_PRICE, PRODUCT_ID) VALUES (3, 2, 1, 100.00, 1);
INSERT INTO OPERATION_PRODUCT (OPERATION_PRODUCT_ID, OP_ID, QUANTITY, SALE_PRICE, PRODUCT_ID) VALUES (4, 2, 1, 90.00, 2);
INSERT INTO OPERATION_PRODUCT (OPERATION_PRODUCT_ID, OP_ID, QUANTITY, SALE_PRICE, PRODUCT_ID) VALUES (5, 2, 1, 100.00, 3);
INSERT INTO OPERATION_PRODUCT (OPERATION_PRODUCT_ID, OP_ID, QUANTITY, SALE_PRICE, PRODUCT_ID) VALUES (6, 3, 1, 120.00, 4);
INSERT INTO OPERATION_PRODUCT (OPERATION_PRODUCT_ID, OP_ID, QUANTITY, SALE_PRICE, PRODUCT_ID) VALUES (7, 3, 1, 70.00, 5);
INSERT INTO OPERATION_PRODUCT (OPERATION_PRODUCT_ID, OP_ID, QUANTITY, SALE_PRICE, PRODUCT_ID) VALUES (8, 3, 1, 60.00, 6);
INSERT INTO OPERATION_PRODUCT (OPERATION_PRODUCT_ID, OP_ID, QUANTITY, SALE_PRICE, PRODUCT_ID) VALUES (1, 1, 1, 100.00, 1);
INSERT INTO OPERATION_PRODUCT (OPERATION_PRODUCT_ID, OP_ID, QUANTITY, SALE_PRICE, PRODUCT_ID) VALUES (2, 1, 1, 100.00, 2);

COMMIT WORK;