INSERT INTO COM11.OPERATION_PRODUCT (OPERATION_PRODUCT_ID, OP_ID, QUANTITY, SALE_PRICE, PRODUCT_ID) VALUES (OPERATION_PRODUCT_SEQ.nextval, 2, 1, (select PRODUCT_USE.SELL_PRICE from PRODUCT_USE where PRODUCT_USE.PRODUCT_ID = 1), 1);
INSERT INTO COM11.OPERATION_PRODUCT (OPERATION_PRODUCT_ID, OP_ID, QUANTITY, SALE_PRICE, PRODUCT_ID) VALUES (OPERATION_PRODUCT_SEQ.nextval, 2, 1, (select PRODUCT_USE.SELL_PRICE from PRODUCT_USE where PRODUCT_USE.PRODUCT_ID = 2), 2);
INSERT INTO COM11.OPERATION_PRODUCT (OPERATION_PRODUCT_ID, OP_ID, QUANTITY, SALE_PRICE, PRODUCT_ID) VALUES (OPERATION_PRODUCT_SEQ.nextval, 2, 1, (select PRODUCT_USE.SELL_PRICE from PRODUCT_USE where PRODUCT_USE.PRODUCT_ID = 3), 3);
INSERT INTO COM11.OPERATION_PRODUCT (OPERATION_PRODUCT_ID, OP_ID, QUANTITY, SALE_PRICE, PRODUCT_ID) VALUES (OPERATION_PRODUCT_SEQ.nextval, 3, 1, (select PRODUCT_USE.SELL_PRICE from PRODUCT_USE where PRODUCT_USE.PRODUCT_ID = 4), 4);
INSERT INTO COM11.OPERATION_PRODUCT (OPERATION_PRODUCT_ID, OP_ID, QUANTITY, SALE_PRICE, PRODUCT_ID) VALUES (OPERATION_PRODUCT_SEQ.nextval, 3, 1, (select PRODUCT_USE.SELL_PRICE from PRODUCT_USE where PRODUCT_USE.PRODUCT_ID = 5), 5);
INSERT INTO COM11.OPERATION_PRODUCT (OPERATION_PRODUCT_ID, OP_ID, QUANTITY, SALE_PRICE, PRODUCT_ID) VALUES (OPERATION_PRODUCT_SEQ.nextval, 3, 1, (select PRODUCT_USE.SELL_PRICE from PRODUCT_USE where PRODUCT_USE.PRODUCT_ID = 6), 6);


