
--ETL by date
insert into FACT_SALE
select t.TIME_ID, bb.EMP_ID, bb.CLINIC_ID, bb.DOCTOR_ID, bb.TOTAL_AMOUNT
from (
         select TRUNC(b.BILL_DATE) as BILL_DATE, b.EMP_ID, b.CLINIC_ID, b.DOCTOR_ID, sum(b.TOTAL_AMOUNT) as TOTAL_AMOUNT
         from BILL b
         group by TRUNC(b.BILL_DATE), b.EMP_ID, b.CLINIC_ID, b.DOCTOR_ID
     ) bb
         inner join TIME t on TRUNC(t.DATE_AT) = bb.BILL_DATE
;



SELECT
    SUM(FACT_SALE.AMOUNT) AS AMOUNT, CLINIC.CLINIC_NAME , SALES_STAFF.EMP_FULL_NAME
FROM
    FACT_SALE , CLINIC , SALES_STAFF , TIME
WHERE
        TIME.DATE_AT >= TO_DATE('2021/12/01', 'YYYY/MM/DD')
  AND TIME.DATE_AT <= TO_DATE('2021/12/31', 'YYYY/MM/DD')
  AND FACT_SALE.TIME_ID = TIME.TIME_ID
  AND CLINIC.CLINIC_ID = FACT_SALE.CLINIC_ID
  AND FACT_SALE.SALES_STAFF_ID = SALES_STAFF.EMP_ID
GROUP BY CLINIC.CLINIC_NAME ,  SALES_STAFF.EMP_FULL_NAME


